---
title: "charts"
output: html_document
---






```{r}

m_eqn = function(m) {

  l <- list(a = format(coef(m)[1], digits = 2),
      b = format(abs(coef(m)[2]), digits = 2),
      r2 = format(summary(m)$r.squared, digits = 3));

  if (coef(m)[2] >= 0)  {
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2,l)
  } else {
    eq <- substitute(italic(y) == a - b %.% italic(x)*","~~italic(r)^2~"="~r2,l)    
  }

  as.character(as.expression(eq));                 
}

#Scatter plot of ABV v IBU
ggplot(styles, aes(x=abv, y=ibu)) +
  geom_point(color = misc_cool,
             size = 3) +
  geom_smooth(method = "lm", 
              se = FALSE, 
              color=misc_warm) +
  geom_text(aes(x = .045, 
                y = 125, 
                label = lm_eqn(lm(abv ~ ibu ,styles))), 
            parse = TRUE, 
            color = misc_warm) +
  theme(legend.position="none") +
  ggtitle("Alcohol Content v Bitterness") +
  xlab("Alcohol Content (%)") +
  ylab("International Bitterness Units (IBU)") +
  theme(plot.title = element_text(hjust = 0.5, size = 24))

ggsave("../figure/abv_ibu_scatter.tiff", units="in", width=10, height=7, dpi=400, compression = 'lzw')


```



```{r}
ggplot((styles %>% drop_na(abv)), aes(x="", y=abv)) +
      geom_point(aes(fill = ifelse((abv %in% abv_outliers),"Outlier","Valid")), 
                 size = 4, 
                 shape = 21, 
                 position = position_jitter())+
      stat_boxplot(geom ='errorbar') +
      geom_boxplot(alpha=.5, 
                   outlier.shape = NA) +
      guides(fill=guide_legend(title= NULL)) +
      xlab(NULL) +
      ylab("Alcohol by Volume (%)") +
      scale_y_continuous(position = "right", 
                         breaks = c(.025, .05, .075, .1, .125), 
                         limits = c(0.025, .125)) +
      scale_fill_manual(values = c('#cc0606', abv_fill)) +
      theme(plot.title = element_text(hjust = 0.5, size = 22),
            axis.title.y=element_blank(),
            axis.title.x=element_text(size = 24)) +
      coord_flip()


ggsave("../figure/abv_boxplot.tiff", units="in", width=14, height=3, dpi=400, compression = 'lzw')

ggplot((styles %>% drop_na(ibu)), aes(x="", y=ibu)) +
      geom_point(aes(fill = ifelse((ibu %in% ibu_outliers),"Outlier","Valid")),
                 size = 4, 
                 shape = 21, 
                 position = position_jitter())+
      stat_boxplot(geom ='errorbar') +
      geom_boxplot(alpha = .5, 
                   outlier.shape = NA) +
      guides(fill=guide_legend(title= NULL)) +
      xlab(NULL) +
      ylab("International Bitterness Units (IBU)") +
      scale_y_continuous(breaks = c(0, 25, 50, 75, 100, 125, 150), 
                         limits = c(0, 150)) +
      scale_fill_manual(values = c('#cc0606', ibu_fill)) +
      theme(plot.title = element_text(hjust = 0.5, size = 22),
            axis.title.y=element_blank(),
            axis.title.x=element_text(size = 24)) +
      coord_flip()


ggsave("../figure/ibu_boxplot.tiff", units="in", width=14, height=3, dpi=400, compression = 'lzw')


```




```{r}
ggplot(merged_by_state, 
       aes(x=state, y=abv)) +
  geom_bar(stat = "identity",  
           fill = abv_fill, 
           color = abv_outline, 
           width=1) +
  theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=0, vjust = .3))  +
  theme(legend.position="none") +
  ggtitle("Median Alcohol Content by State") +
  xlab("Alcohol Content (%)") +
  ylab("International Bitterness Units (IBU)") +
  theme(plot.title = element_text(hjust = 0.5, size = 18))
  
  ggsave("../figure/abv_bar.tiff", units="in", width=11, height=6, dpi=400, compression = 'lzw')

```

```{r}

ggplot(merged_by_state, 
       aes(x=state, y=ibu)) +
  geom_bar(stat = "identity",  
           fill = ibu_fill, 
           color = ibu_outline, 
           width=1) +
  theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1)) +
  theme(legend.position="none") +
  ggtitle("Median Bitterness by State") +
  xlab("Alcohol Content (%)") +
  ylab("International Bitterness Units (IBU)") +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

  ggsave("../figure/ibu_bar.tiff", units="in", width=11, height=6, dpi=400, compression = 'lzw')

```



```{r}
ggplot((breweries_geo %>% arrange(desc(brewery_count))), 
       aes(group = state, stat="identity")) +
  geom_polygon(aes(x = long, 
                   y = lat, 
                   group=group, 
                   fill=brewery_count), 
               color = "black") + 
  geom_text(data = (breweries_by_state %>% 
                    filter(!(state %in% c("AK", "DC", "HI")))), #filter to continental 50 states
            aes(x = lon_center, 
                y = lat_center, 
                label = as.character(brewery_count)),
            color = 'white'
            ) +
  guides(fill=guide_legend(title= "Brewery Count")) +
  scale_fill_continuous(breaks = seq(0,50, by = 5)) +
  coord_fixed(1.3) + # fix lat/long display ratio
  ggtitle("Breweries by State") + # set plot title
  theme(plot.title = element_text(hjust = 0.5)) + # center plot title
  theme(legend.position = "left",
        axis.title.x=element_blank(), # hide x axis title
        axis.text.x=element_blank(),  # hide x axis text
        axis.ticks.x=element_blank(), # hide x axis ticks
        axis.title.y=element_blank(), # hide y axis title
        axis.text.y=element_blank(),  # hide y axis text
        axis.ticks.y=element_blank()) # hide y axis ticks


  ggsave("../figure/brweeries_geo.tiff", units="in", width=10, height=10, dpi=400, compression = 'lzw')

```










```{r}

# Map MAX ABV by STATE

x <- select(merged_data, state, abv) %>%
                   na.omit() %>%
                   group_by(state) %>%
                    summarise_all(max) %>%
                   arrange(desc(abv)) %>%
                    left_join(state_ll, by=c("state" = "Abbr"))

breweries_geo2 <- x %>%
                  inner_join(states, by = c("name" = "name")) 





ggplot((breweries_geo2 %>% arrange(desc(abv))), 
       aes(group = state, stat="identity")) +
  geom_polygon(aes(x = long, 
                   y = lat, 
                   group=group, 
                   fill=abv), 
               color = "black") + 
  geom_text(data = (x %>% 
                    filter(!(state %in% c("AK", "DC", "HI")))), #filter to continental 50 states
            aes(x = lon_center, 
                y = lat_center, 
                label = as.character(round(abv, 2))),
            color = 'white',
            size = 4
            ) +
  scale_fill_gradient(low=abv_fill, high='#8E5C05') +
  guides(fill=guide_legend(title= "Brewery Count")) +
  coord_fixed(1.3) + # fix lat/long display ratio
  ggtitle("Breweries by State") + # set plot title
  theme(plot.title = element_text(hjust = 0.5)) + # center plot title
  theme(legend.position = "left",
        axis.title.x=element_blank(), # hide x axis title
        axis.text.x=element_blank(),  # hide x axis text
        axis.ticks.x=element_blank(), # hide x axis ticks
        axis.title.y=element_blank(), # hide y axis title
        axis.text.y=element_blank(),  # hide y axis text
        axis.ticks.y=element_blank()) # hide y axis ticks



  ggsave("../figure/max_abv_geo.tiff", units="in", width=10, height=10, dpi=400, compression = 'lzw')

# MAX IBU by STATE

x <- select(merged_data, state, ibu) %>%
                   na.omit() %>%
                   group_by(state) %>%
                    summarise_all(max) %>%
                   arrange(desc(ibu)) %>%
                    full_join(state_ll, by=c("state" = "Abbr"))

breweries_geo2 <- x %>%
                  inner_join(states, by = c("name" = "name")) 





ggplot((breweries_geo2 %>% arrange(desc(ibu))), 
       aes(group = state, stat="identity")) +
  geom_polygon(aes(x = long, 
                   y = lat, 
                   group=group, 
                   fill=ibu), 
               color = "black") + 
  geom_text(data = (x %>% 
                    filter(!(state %in% c("AK", "DC", "HI")))), #filter to continental 50 states
            aes(x = lon_center, 
                y = lat_center, 
                label = as.character(ibu)),
            color = 'white'
            ) +
  scale_fill_gradient(low=ibu_fill, high='#035C64') +
  guides(fill=guide_legend(title= "Brewery Count")) +
  coord_fixed(1.3) + # fix lat/long display ratio
  ggtitle("Breweries by State") + # set plot title
  theme(plot.title = element_text(hjust = 0.5)) + # center plot title
  theme(legend.position = "left",
        axis.title.x=element_blank(), # hide x axis title
        axis.text.x=element_blank(),  # hide x axis text
        axis.ticks.x=element_blank(), # hide x axis ticks
        axis.title.y=element_blank(), # hide y axis title
        axis.text.y=element_blank(),  # hide y axis text
        axis.ticks.y=element_blank()) # hide y axis ticks


  ggsave("../figure/max_ibu_geo.tiff", units="in", width=10, height=10, dpi=400, compression = 'lzw')



```



```{r}

(select(styles, style) %>%
na.omit() %>%
summarize_all(funs(ct = n_distinct(.))))[1,]
```

