---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually makes debugging easier, and sometimes half a codebook
                # is better than none
  echo = FALSE  # don't show the R code
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)


prep_data_frame <- function(codebook_data) {
  detect_missings(codebook_data,
      only_labelled_missings = TRUE, # only labelled values are autodetected as
                                     # missing
      negative_values_are_missing = FALSE, # negative values are NOT missing values
      ninety_nine_problems = TRUE   # 99/999 are missing values, if they
                                     # are more than 5 MAD from the median
      )
  
  # If you are not using formr, the codebook package needs to guess which items
  # form a scale. The following line finds item aggregates with names like this:
  # scale = scale_1 + scale_2R + scale_3R
  # identifying these aggregates allows the codebook function to
  # automatically compute reliabilities.
  # However, it will not reverse items automatically.
  detect_scales(codebook_data)
  
  }

```




Sometimes, the metadata is not set up in such a way that codebook
can leverage it fully. These functions help fix this.

```{r codebook}
library(codebook) # load the package



beer_data_clean <- prep_data_frame(read.csv('data/beer_clean.csv'))
breweries_data_clean <- prep_data_frame(read.csv('data/breweries_clean.csv'))

codebook(breweries_data_clean,beer_data_clean )







# omit the following lines, if your missing values are already properly labelled


```

Now, generating a codebook is as simple as calling codebook from a chunk in an
rmarkdown document.

```{r}
# df <- read.csv('data/beer_clean.csv')
# #as.data.frame(df %>% rename(Y = X))
# 
# attributes(df)
```

