---
title: "sandbox2"
author: "Brock Friedrich"
date: "June 19, 2018"
output: html_document
---



```{r setup}
require(dplyr)
require(tidyr)
require(knitr)
require(ggplot2)
require(maps)
require(RColorBrewer)
require(summarytools)

#automatically set working directory to the directory containing this R script

```

##Import Breweries Data
```{r}


summary(breweries_data)

summary(beer_data)


#(as.data.frame(summarytools::descr(breweries_data)),digits = 2)

#view(freq(breweries_data$State, order = "freq"))



```


## Impute IBU
```{r fig.height=20, fig.width=30}

beer_data %>% distinct(Style)


notnull <- beer_data %>% filter(is.na(IBU)) %>% distinct(Style)


isnull <- beer_data %>% filter(!is.na(IBU)) %>% distinct(Style, IBU, ABV, Ounces) %>% arrange(Style)


#A distinct list of beer styles. A distinct beer style is noted as having a unique style name, IBU, ABV, and Ounces values.
styles <- notnull %>% 
          full_join(isnull, by = "Style") %>% arrange(Style) #%>%
          #mutate_each(funs(as.character), Style)



#Summary statistics for each unique beer Stlye
summary_by_style <- styles %>%
  dplyr::group_by(Style) %>%
  dplyr::summarize_each(funs(count=n_distinct(.), min(.), max(.), mean(.), median(.), sd(.)))
  #select_if(function(x) any(is.na(x))) %>%
  #summarise_all(funs(sum(is.na(.))))

ggplot(styles, aes(x=Style, y=IBU, fill=Ounces)) +
    geom_boxplot() +
    theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1)) 

ggplot(styles, aes(x=reorder(Style, ABV, FUN=median), y=ABV,  fill=Ounces)) +
    geom_boxplot() +
    theme_light() +
    theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1))
    



```


### IBU Transform
```{r}

styles$IBU_log <- log(styles$IBU)

ggplot(styles) +
    geom_histogram(aes(x=IBU)) +
    theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1)) 


#IBU_log_mean <- mean(styles$IBU_log)

ggplot(styles) +
    geom_histogram(aes(x=IBU_log)) +
#    geom_vline(xintercept = IBU_log_mean) +
    theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1)) 

```


## ABV Transform
```{r }
#fig.height=20, fig.width=30

styles$ABV_log <- log(styles$ABV)

ggplot(styles) +
    geom_histogram(aes(x=ABV)) +
    theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1)) 

ggplot(styles) +
    geom_histogram(aes(x=ABV_log)) +
    theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1)) 



ggplot(styles, aes(x=Ounces, y=ABV, group=Ounces)) +
    geom_boxplot() +
    #geom_point(position=position_dodge(width=0.75),aes(group=Ounces)) +
    #scale_fill_manual(values = Ounces) +
    #scale_x_discrete(limits = c("8.4","12.0","16.0","16.9","19.2","24.0","32.0","NA")) +
    theme_light() +
    theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1))
    



styles$Ounces <- as.character(styles$Ounces)

styles %>% distinct(Ounces) %>% select(Ounces)

ggplot(styles, aes(x=reorder(Style, ABV, FUN=median), y=ABV)) +
    geom_boxplot() +
    theme_light() +
    theme(text = element_text(size=10),
        axis.text.x = element_text(angle=90, hjust=1))
    

```






```{r}

s <- as.data.frame(seq(1, 100))

s$qual <- ifelse(s > 3, "Valid", "Error")

# ggplot(s, aes(x="", y=qual, fill=qual))+
# geom_bar(width = 1, stat = "identity") +
# scale_fill_brewer(palette="Dark2") +
# coord_polar("y", start=0) +
# geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
#         label = percent(value/100)), size=5)


```

